export const REGISTER_USER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_FAIL";
export const LOGOUT_USER = "LOGOUT";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
